## $$Numpy\ Guide$$

In [69]:
import numpy as np

In [70]:
# arange(n) 创建一个含有整数0到n-1的数组
def numpysum(n):
    a=np.arange(n)**2
    b=np.arange(n)**3
    c=a+b
    return c
numpysum(3)

array([ 0,  2, 12])

In [71]:
# 计算某个函数或语句的运行耗时
from datetime import datetime
start=datetime.now()
numpysum(1000)
delta=datetime.now()-start
print "Time consumed %d microseconds"%(delta.microseconds)

Time consumed 0 microseconds


In [77]:
#numpy中的多维数组称为ndarray
#使用array()创建多维数组
a=np.array([np.arange(2),np.arange(2)])
a

array([[0, 1],
       [0, 1]])

In [73]:
#shape属性显示数组形状
a.shape

(2L, 2L)

In [75]:
#通过下标选取元素
a[0,0],a[0,1],a[1,0],a[1,1]

(0, 1, 0, 1)

In [80]:
#类型转换
np.float64(42)

33

In [83]:
#用dtype为数组指定数据类型
np.arange(7,dtype=np.uint16)

array([0, 1, 2, 3, 4, 5, 6], dtype=uint16)

In [86]:
#不允许由复数转换为整数
np.float(42.0+1.0j)

TypeError: can't convert complex to float

In [91]:
#使用real()函数和imag()函数提取复数的实部和虚部
c=42+2j
np.real(c),np.imag(c)

(array(42.0), array(2.0))

In [93]:
#某数据类型占用的字节数的数目存在类dtype的itemsize里
a.dtype.itemsize

4

In [95]:
#创建数据类型
np.dtype(float)

dtype('float64')

In [96]:
#显示所有的数据类型的字符码
np.sctypeDict.keys()

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 'unicode',
 23,
 'cfloat',
 'longfloat',
 'Int32',
 'Complex64',
 'unicode_',
 'complex',
 'timedelta64',
 'uint16',
 'c16',
 'float32',
 'int32',
 'D',
 'H',
 'void',
 'unicode0',
 'L',
 'P',
 'half',
 'void0',
 'd',
 'h',
 'l',
 'p',
 22,
 'Timedelta64',
 'object0',
 'b1',
 'M8',
 'String0',
 'float16',
 'ulonglong',
 'i1',
 'uint32',
 '?',
 'Void0',
 'complex64',
 'G',
 'O',
 'UInt8',
 'S',
 'byte',
 'UInt64',
 'g',
 'float64',
 'ushort',
 'float_',
 'uint',
 'object_',
 'Float16',
 'complex_',
 'Unicode0',
 'uintp',
 'intc',
 'csingle',
 'datetime64',
 'float',
 'bool8',
 'Bool',
 'intp',
 'uintc',
 'bytes_',
 'u8',
 'u4',
 'int_',
 'cdouble',
 'u1',
 'complex128',
 'u2',
 'f8',
 'Datetime64',
 'ubyte',
 'm8',
 'B',
 'uint0',
 'F',
 'bool_',
 'uint8',
 'c8',
 'Int64',
 'Int8',
 'Complex32',
 'V',
 'int8',
 'uint64',
 'b',
 'f',
 'double',
 'UInt32',
 'clongdouble',
 'str',
 'f2',
 '

In [98]:
#通过chara属性获取某数据类型对应的字符码
np.dtype(float).char

'd'

In [99]:
#通过type属性获取其类型
np.dtype(float).type

numpy.float64

In [102]:
#str属性保存表示数据类型的字符串
#其中第一个数据类型表示字节顺序：
#    字节顺序：占内存多于一个字节的类型的存放顺序
#        大端顺序：低字节数据存放在内存高地址处，用符号'>'表示
#        小端顺序：低字节数据存放在内存低地址处，用符号'<'表示
#如果需要，后面跟字符码和数字，用来表示存储每个数组元素需要的字节数
np.dtype(float).str

'<f8'

In [103]:
#常规切片操作
np.arange(7)[2:5]

array([2, 3, 4])

In [104]:
#固定步长的切片操作
np.arange(7)[:7:2]

array([0, 2, 4, 6])

In [105]:
#使用切片操作倒序数组
np.arange(7)[::-1]

array([6, 5, 4, 3, 2, 1, 0])

In [107]:
#reshape()函数调整数组形状
b=np.arange(24).reshape(2,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [110]:
#ravel()函数将多维数组平铺为一维数组，返回数组的视图
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [111]:
#flatten()函数将多维数组平铺为一维数组，但返回的是真实的数组,需要分配新的内存空间 ???
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [115]:
#用元组定义数组形状
b.shape=(6,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [116]:
#矩阵转置
b.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [118]:
#resize()函数类似reshape()，但是会改变所作用的数组
b.resize((2,12))
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [121]:
#hstack()函数实现数组的水平叠加
a=np.arange(9).reshape(3,3)
b=a*2
np.hstack((a,b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [123]:
#用concatenate()实现相同效果
#数组的axis属性：
#    对于二维数组：0表示列，1表示行
#    对于三维数组：将其看成若干二维数组的叠加；0表示叠加方向，1表示二维数组的列，2表示二维数组的行
np.concatenate((a,b),axis=1) #沿行方向合并

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [124]:
#vstack()实现垂直叠加
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [125]:
#用concatenate()实现相同效果
np.concatenate((a,b),axis=0) #沿列方向合并

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [126]:
#用dstack()实现深度叠加，比如在一个图像数据的二维数组上叠加另一幅图像的数据
np.dstack((a,b))

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

In [127]:
#column_stack()函数对一维数组进行列式堆叠
oned=np.arange(2)
twod=2*oned
np.column_stack((oned,twod))

array([[0, 0],
       [1, 2]])

In [128]:
#column)stack()作用于二维数组与hstack()相似
np.column_stack((a,b))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

In [129]:
#row_stack()函数对一维数组行式堆叠
np.row_stack((oned,twod))

array([[0, 1],
       [0, 2]])

In [5]:
#row_stack()函数作用于二维数组与vstack()相似
import pandas as pd
a=pd.DataFrame({'A':[1,2,3],'B':[4,5,6]})
for item in a[['A','B']]:
    print item[0]

A
B
